name: flame_3d_flight_poc
description: A Flight game that serves as a Proof of concept for the Flame 3D package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  audioplayers: ^6.5.1
  bloc: ^9.0.1
  equatable: ^2.0.7
  flame: ^1.32.0
  flame_3d: ^0.1.1+4
  flame_audio: ^2.11.10
  flame_behaviors: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.2
  intl: ^0.20.2

dev_dependencies:
  bloc_test: ^10.0.0
  flame_test: ^2.0.3
  flutter_test:
    sdk: flutter
  mockingjay: ^2.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
    - assets/objects/
